### ISSUE TITLE
Deformable Transformer Encoder is not available.

### ISSUE THREAD

**Issue by kavmar** [microsoft/BiomedParse#33]
Hi,

I am trying example_prediction.py or inference_examples_DICOM.py and I am getting a message **Deformable Transformer Encoder is not available.** This is the same as in inference_examples_DICOM.ipynb after running the first kernel. 

/home/me/anaconda3/envs/biomedparse/bin/python /home/me/PycharmProjects/BiomedParse/inference_examples_DICOM.py 
Deformable Transformer Encoder is not available.
/home/me/anaconda3/envs/biomedparse/lib/python3.9/site-packages/kornia/feature/lightglue.py:30: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
/home/me/anaconda3/envs/biomedparse/lib/python3.9/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/me/PycharmProjects/BiomedParse/inference_examples_DICOM.py", line 10, in <module>
    from inference_utils.inference import interactive_infer_image
  File "/home/me/PycharmProjects/BiomedParse/inference_utils/inference.py", line 34, in <module>
    from .output_processing import mask_stats, combine_masks
  File "/home/me/PycharmProjects/BiomedParse/inference_utils/output_processing.py", line 6, in <module>
    target_dist = json.load(open("inference_utils/target_dist.json"))
  File "/home/me/anaconda3/envs/biomedparse/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/me/anaconda3/envs/biomedparse/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/me/anaconda3/envs/biomedparse/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/me/anaconda3/envs/biomedparse/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

Thanks for advice

**Comment by Adibvafa** [comment]
There seems to be an issue during cloning where the content of the file [target_dist.json](https://github.com/microsoft/BiomedParse/blob/main/inference_utils/target_dist.json) changes unexpectedly. Locate the file, and change its content to whatever is on the GitHub manually. It should fix the problem.

You can ignore `Deformable Transformer Encoder is not available` since inference is still possible despite it.
